import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const { toolType, subject, topic, class: className, difficulty, questionCount } = await req.json();

    let content = '';

    switch (toolType) {
      case 'worksheet':
        content = generateWorksheet(subject, topic, className, difficulty, parseInt(questionCount));
        break;
      case 'notes':
        content = generateNotes(subject, topic, className);
        break;
      case 'mindmap':
        content = generateMindmap(subject, topic, className);
        break;
      case 'test':
        content = generateTestPaper(subject, topic, className, difficulty, parseInt(questionCount));
        break;
      case 'attendance':
        content = generateAttendanceTemplate(className);
        break;
      case 'homework':
        content = generateHomeworkTemplate(subject, topic, className);
        break;
      case 'parent':
        content = generateParentCommunication(subject, topic, className);
        break;
      default:
        content = 'Invalid tool type selected.';
    }

    return NextResponse.json({ content });
  } catch (error) {
    console.error('Teacher Tools API Error:', error);
    return NextResponse.json(
      { error: 'Failed to generate content' },
      { status: 500 }
    );
  }
}

function generateWorksheet(subject: string, topic: string, className: string, difficulty: string, questionCount: number): string {
  const date = new Date().toLocaleDateString('en-IN');

  return `# ${subject} Worksheet
**Class:** ${className} | **Topic:** ${topic} | **Date:** ${date}
**Difficulty Level:** ${difficulty.toUpperCase()}

---

## Instructions:
1. Answer all questions in your notebook
2. Show all steps clearly for numerical problems
3. Time allowed: ${Math.ceil(questionCount * 2)} minutes
4. Total marks: ${questionCount * 2}

---

## Questions:

${generateQuestions(subject, topic, questionCount, difficulty)}

---

## Answer Key (For Teachers):

${generateAnswerKey(subject, topic, questionCount)}

---

**Note for Students:** यह worksheet tumhari practice ke liye hai। हर question को dhyan se solve karo aur agar doubt ho toh teacher se zaroor poocho! 📚

**Generated by SmartEd Tutor & Assistant**
`;
}

function generateNotes(subject: string, topic: string, className: string): string {
  return `# ${subject} - ${topic}
**Class ${className} | Comprehensive Notes**

---

## 📌 Topic Overview

${topic} ek important concept hai jo Class ${className} ${subject} syllabus ka core part hai।

---

## 🎯 Learning Objectives

- Understand the basic concepts of ${topic}
- Apply knowledge in problem-solving
- Connect with real-life applications
- Prepare for exams effectively

---

## 📖 Key Concepts

### 1. Definition
${topic} is a fundamental concept in ${subject} that...

### 2. Important Points
- **Point 1:** Key concept explanation
- **Point 2:** Related theory or formula
- **Point 3:** Important properties or characteristics
- **Point 4:** Special cases or exceptions

### 3. Formulas / Rules
\`\`\`
Key Formula or Rule related to ${topic}
\`\`\`

### 4. Examples
**Example 1:** Simple illustrative example
- Step 1: Setup
- Step 2: Process
- Step 3: Solution

**Example 2:** Slightly advanced example
- Application of concept
- Solution approach

---

## 💡 Important Tips

✅ **Remember:** Main points ko highlight karo
✅ **Practice:** Regular revision is key
✅ **Application:** Real-life examples se connect karo
✅ **Exam Tip:** Ye topic exams me important hai!

---

## 🔍 Common Mistakes to Avoid

❌ Mistake 1: Common error students make
❌ Mistake 2: Another frequent misconception
❌ Mistake 3: Calculation or conceptual error

---

## 📝 Quick Revision Points

1. Main definition yaad rakho
2. Key formulas practice karo
3. Examples solve karte raho
4. Previous year questions dekho

---

## 🎓 Exam-Important Questions

**Short Answer Questions (2-3 marks):**
1. Define ${topic} and give one example
2. State the key principle/formula
3. Differentiate between related concepts

**Long Answer Questions (5-6 marks):**
1. Explain ${topic} with detailed examples
2. Derive the main formula/principle
3. Apply concept to solve complex problems

---

## 🌟 Additional Resources

- Practice questions: Textbook Chapter Exercises
- Reference: NCERT Class ${className} ${subject}
- Online resources: Educational videos on ${topic}

---

**Remember:** Concepts ko samajhna zaroori hai, ratta lagane se better hai understanding build karo! 📚✨

**Prepared by SmartEd Tutor & Assistant**
`;
}

function generateMindmap(subject: string, topic: string, className: string): string {
  return `# Mind Map: ${topic}
**Subject:** ${subject} | **Class:** ${className}

---

## Central Concept: ${topic}

\`\`\`
                            ${topic}
                               |
        _______________________|_______________________
       |            |            |            |        |
   Branch 1     Branch 2     Branch 3     Branch 4  Branch 5
       |            |            |            |        |
    Detail 1    Detail 2     Detail 3     Detail 4  Detail 5
\`\`\`

---

## Branch 1: Basic Definition
- What is ${topic}?
- Origin/Background
- Importance in ${subject}

## Branch 2: Key Concepts
- Main principle/theory
- Related formulas
- Important properties

## Branch 3: Types/Categories
- Type A
- Type B
- Type C

## Branch 4: Applications
- Real-life examples
- Practical uses
- Problem-solving techniques

## Branch 5: Related Topics
- Connected concept 1
- Connected concept 2
- Advanced extensions

---

## 🔗 How to Use This Mind Map

1. **Center pe focus karo:** ${topic} ko main concept samjho
2. **Branches explore karo:** Har branch ek sub-topic hai
3. **Connections banao:** Kaise sab related hain wo samjho
4. **Visual memory use karo:** Diagram draw karke yaad karo

---

## 📌 Quick Memory Tips

**Acronym:** Create a word using first letters of each branch
**Visual:** Draw this with colors and icons
**Story:** Connect all branches in a story format

---

**Mind mapping tip:** Apne haath se bhi draw karo - writing helps memory! 🎨🧠

**Generated by SmartEd Tutor & Assistant**
`;
}

function generateTestPaper(subject: string, topic: string, className: string, difficulty: string, questionCount: number): string {
  const date = new Date().toLocaleDateString('en-IN');
  const totalMarks = questionCount * 3;
  const duration = Math.ceil(questionCount * 3);

  return `# ${subject} Test Paper
**Class:** ${className} | **Topic:** ${topic}
**Date:** ${date} | **Duration:** ${duration} minutes | **Total Marks:** ${totalMarks}

---

## Instructions to Students:

1. Read all questions carefully before attempting
2. Attempt all questions
3. Show all working/steps for numerical problems
4. Write neat and legible answers
5. Marks are indicated against each question

---

## Section A: Multiple Choice Questions (1 mark each)

${generateMCQs(subject, topic, Math.ceil(questionCount / 3))}

---

## Section B: Short Answer Questions (3 marks each)

${generateShortAnswerQuestions(subject, topic, Math.ceil(questionCount / 3))}

---

## Section C: Long Answer Questions (5 marks each)

${generateLongAnswerQuestions(subject, topic, Math.floor(questionCount / 3))}

---

## Marking Scheme (For Teachers)

### Section A Answers:
${generateMCQAnswers(Math.ceil(questionCount / 3))}

### Section B Marking Points:
- Clear explanation: 1.5 marks
- Correct example/calculation: 1 mark
- Proper conclusion: 0.5 marks

### Section C Marking Points:
- Introduction/definition: 1 mark
- Main explanation/derivation: 2.5 marks
- Examples/applications: 1 mark
- Conclusion: 0.5 marks

---

**Good Luck! 🎯**

**Test generated by SmartEd Tutor & Assistant**
`;
}

function generateAttendanceTemplate(className: string): string {
  return `# Attendance Register Template
**Class:** ${className} | **Month:** ${new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}

---

## Daily Attendance Sheet

| Roll No. | Student Name | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | Total P | Total A | % |
|----------|-------------|---|---|---|---|---|---|---|---|---|----|----|----|----|----|----|---------|---------|----|
| 1        | Student 1   |   |   |   |   |   |   |   |   |   |    |    |    |    |    |    |         |         |    |
| 2        | Student 2   |   |   |   |   |   |   |   |   |   |    |    |    |    |    |    |         |         |    |
| 3        | Student 3   |   |   |   |   |   |   |   |   |   |    |    |    |    |    |    |         |         |    |
| 4        | Student 4   |   |   |   |   |   |   |   |   |   |    |    |    |    |    |    |         |         |    |
| 5        | Student 5   |   |   |   |   |   |   |   |   |   |    |    |    |    |    |    |         |         |    |

**Legend:**
- P = Present
- A = Absent
- L = Late
- H = Holiday

---

## Monthly Summary

### Class Statistics:
- **Total Students:** _____
- **Average Attendance:** _____%
- **Days Conducted:** _____

### Students with Low Attendance (<75%):
1. ___________________ (___%)
2. ___________________ (___%)
3. ___________________ (___%)

---

## Action Required:

- [ ] Contact parents of students with <75% attendance
- [ ] Send attendance report to administration
- [ ] Update digital records
- [ ] Issue attendance warnings if needed

---

## Notes:

_Use this space for any special remarks about attendance patterns or issues_

---

**Teacher Signature:** ________________
**Date:** ________________

**Generated by SmartEd Tutor & Assistant**
`;
}

function generateHomeworkTemplate(subject: string, topic: string, className: string): string {
  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + 7);

  return `# Homework Assignment
**Class:** ${className} | **Subject:** ${subject}
**Topic:** ${topic}
**Date Assigned:** ${new Date().toLocaleDateString('en-IN')}
**Due Date:** ${dueDate.toLocaleDateString('en-IN')}

---

## Learning Objectives:
By completing this homework, students will be able to:
- ✅ Understand key concepts of ${topic}
- ✅ Apply learned concepts to solve problems
- ✅ Develop analytical and critical thinking skills

---

## Instructions:
1. Complete all questions in your homework notebook
2. Write the question before the answer
3. Show all steps and working clearly
4. Submit on or before the due date
5. Use neat and legible handwriting

---

## Part A: Conceptual Questions (10 marks)

**Q1.** Define ${topic} in your own words. (2 marks)

**Q2.** Why is ${topic} important in ${subject}? Give two reasons. (2 marks)

**Q3.** Explain the main principle/concept related to ${topic}. (3 marks)

**Q4.** Give two real-life examples where ${topic} is applied. (3 marks)

---

## Part B: Problem Solving (10 marks)

**Q5.** Solve the following problems related to ${topic}:

*Problem 1:* [Specific problem based on topic] (3 marks)

*Problem 2:* [Medium difficulty problem] (3 marks)

*Problem 3:* [Application-based problem] (4 marks)

---

## Part C: Creative Task (5 marks)

Choose ONE of the following:

**Option 1:** Create a mind map showing all concepts related to ${topic}

**Option 2:** Write a short paragraph explaining ${topic} to a younger student

**Option 3:** Draw a diagram/chart illustrating the concepts of ${topic}

---

## Evaluation Criteria:

| Criteria | Marks |
|----------|-------|
| Completeness | 10 |
| Accuracy | 8 |
| Presentation | 4 |
| Creativity (Part C) | 3 |
| **Total** | **25** |

---

## Additional Practice (Optional):

For students who want extra practice:
- NCERT Textbook: Chapter ___ Questions
- Workbook: Page ___ Exercises
- Online resources: [List relevant educational websites]

---

## Tips for Success:

💡 **Do's:**
- Start early, don't wait for last day
- Refer to your class notes
- If stuck, review examples from class
- Ask doubts in next class

❌ **Don'ts:**
- Don't copy from classmates
- Don't skip steps in numerical problems
- Don't submit incomplete work
- Don't forget to write your name and roll number

---

## Parent/Guardian Note:

Dear Parents,

Please ensure your child completes this homework independently. Your support in monitoring their progress would be appreciated. If your child faces difficulty, please encourage them to ask questions in class.

Thank you for your cooperation! 🙏

---

**Contact:** For any clarifications, please contact during school hours or write in the school diary.

**Generated by SmartEd Tutor & Assistant**
`;
}

function generateParentCommunication(subject: string, topic: string, className: string): string {
  return `# Parent Communication Template
**Class:** ${className} | **Subject:** ${subject}
**Date:** ${new Date().toLocaleDateString('en-IN')}

---

## 📧 Email Template for General Updates

**Subject:** Class ${className} ${subject} - Updates on ${topic}

Dear Parents/Guardians,

Namaste! 🙏

I hope this message finds you and your family in good health.

I am writing to update you about your child's progress in ${subject}, particularly regarding the topic **${topic}** that we have recently covered in class.

### Topics Covered:
- ${topic} - Complete explanation
- Related concepts and applications
- Practical examples and problem-solving

### Upcoming Assessments:
- **Test Date:** ________________
- **Syllabus:** ${topic} and related chapters
- **Marks:** _____ marks
- **Duration:** _____ minutes

### How You Can Help:
1. Ensure your child completes homework regularly
2. Encourage daily revision of class notes
3. Help them maintain a study schedule
4. Ensure they ask doubts in class

### Performance Update:
[Space for individual student feedback]

Please feel free to contact me during school hours (9 AM - 3 PM) if you have any questions or concerns about your child's progress.

Best Regards,
[Teacher Name]
${subject} Teacher
Class ${className}

---

## 📱 WhatsApp Message Template (Short Update)

*Class ${className} - ${subject} Update*

Dear Parents, 🙏

📚 *Recent Topic:* ${topic}

✅ *Homework:* Page ___ Questions ___
📅 *Due Date:* ___________

⚠️ *Important:*
- Test on [Date]
- Complete revision needed
- Submit pending work

For doubts, contact during school hours.

Thank you! 🙏

---

## 📋 Progress Report Template

### Student Performance Report
**Student Name:** ________________
**Class:** ${className}
**Subject:** ${subject}
**Topic:** ${topic}
**Period:** ________________

#### Academic Performance:

| Area | Rating | Comments |
|------|--------|----------|
| Class Participation | ⭐⭐⭐⭐☆ | |
| Homework Completion | ⭐⭐⭐☆☆ | |
| Test Performance | ⭐⭐⭐⭐☆ | |
| Understanding of Concepts | ⭐⭐⭐☆☆ | |

**Strengths:**
- Point 1
- Point 2

**Areas for Improvement:**
- Point 1
- Point 2

**Recommendations:**
- Suggestion 1
- Suggestion 2

**Overall Comment:**
[Detailed feedback about student's progress]

---

## 🔔 Meeting Invitation Template

**Subject:** Parent-Teacher Meeting Invitation

Dear Parents/Guardians,

You are cordially invited to the Parent-Teacher Meeting for Class ${className}.

**Details:**
- **Date:** ________________
- **Time:** ________________
- **Venue:** School Campus / Online (link will be shared)

**Agenda:**
1. Discussion on ${subject} progress
2. Academic performance review
3. Upcoming syllabus and examinations
4. Q&A session

**What to Bring:**
- Student's notebooks
- Previous test papers
- Any concerns or questions

Please confirm your attendance by replying to this message.

Looking forward to meeting you! 🙏

---

## 📞 Concern/Issue Communication Template

**Subject:** Important - Attention Required for [Student Name]

Dear Parents,

I am writing to discuss a matter regarding your child that requires your attention.

**Issue:** [Brief description]

**Observation:** [What has been noticed]

**Impact:** [How this is affecting the student's learning]

**Action Required:**
1. [Specific action 1]
2. [Specific action 2]
3. [Specific action 3]

**Next Steps:**
- Schedule a meeting to discuss further
- Contact: [Phone/Email]
- Best time to reach: [Time slots]

I believe that with your cooperation, we can help your child overcome this challenge.

Warm regards,
[Teacher Name]

---

## 🎉 Appreciation Message Template

**Subject:** Excellent Performance - [Student Name]

Dear Parents,

I am delighted to inform you about the outstanding performance of your child in ${subject}!

**Achievement:**
- Excellent understanding of ${topic}
- Scored [marks] in recent test
- Active class participation
- Helping peers

Keep encouraging this wonderful progress! 🌟

Your child's dedication and hard work are truly commendable.

Congratulations! 👏

Best wishes,
[Teacher Name]

---

**Note:** Always maintain a professional and respectful tone. Be specific about concerns and constructive in feedback. 💼✨

**Generated by SmartEd Tutor & Assistant**
`;
}

// Helper functions for question generation

function generateQuestions(subject: string, topic: string, count: number, difficulty: string): string {
  let questions = '';
  for (let i = 1; i <= count; i++) {
    questions += `**Q${i}.** [${difficulty.toUpperCase()} - 2 marks] Sample question ${i} related to ${topic} in ${subject}\n\n`;
  }
  return questions;
}

function generateAnswerKey(subject: string, topic: string, count: number): string {
  let answers = '';
  for (let i = 1; i <= count; i++) {
    answers += `**A${i}.** Sample answer for question ${i} with key points\n\n`;
  }
  return answers;
}

function generateMCQs(subject: string, topic: string, count: number): string {
  let mcqs = '';
  for (let i = 1; i <= count; i++) {
    mcqs += `**Q${i}.** Sample MCQ question ${i} about ${topic}?\n`;
    mcqs += `   a) Option A\n`;
    mcqs += `   b) Option B\n`;
    mcqs += `   c) Option C\n`;
    mcqs += `   d) Option D\n\n`;
  }
  return mcqs;
}

function generateShortAnswerQuestions(subject: string, topic: string, count: number): string {
  let questions = '';
  for (let i = 1; i <= count; i++) {
    questions += `**Q${i}.** [3 marks] Short answer question ${i} related to ${topic} - Explain with example.\n\n`;
  }
  return questions;
}

function generateLongAnswerQuestions(subject: string, topic: string, count: number): string {
  let questions = '';
  for (let i = 1; i <= count; i++) {
    questions += `**Q${i}.** [5 marks] Long answer question ${i} - Discuss ${topic} in detail with relevant examples and applications.\n\n`;
  }
  return questions;
}

function generateMCQAnswers(count: number): string {
  let answers = '';
  const options = ['a', 'b', 'c', 'd'];
  for (let i = 1; i <= count; i++) {
    const randomOption = options[Math.floor(Math.random() * options.length)];
    answers += `Q${i}: **${randomOption}**\n`;
  }
  return answers;
}
